---

# Set channels/versions for the different operators
pipelines: &channel-pipelines latest
loki: &channel-loki stable
logging: &channel-logging stable
netobserv: &channel-netobserv stable
cert-utils: &channel-cert-utils alpha
cert-manager: &channel-cert-manager stable-v12
quay: &channel-quay stable-3.9
odf: &channel-odf stable-4.13

# The sub-chart helper-operator performs the actual isntallation of the operator.
helper-operator:

  # Enable the Console Plugins for the following Operators
  console_plugins:
    - logging-plugin
    - odf-console
    - netobserv-plugin

  operators:
    #####################
    # OpenShift Pipelines
    #####################
    # Name of the operator (This name will be used as name of the Application in Argo CD)
    openshift-pipelines-operator-rh:
      enabled: true
      # Namespace where the operator shall be installed into
      namespace:
        name: openshift-operators
        # Only create if it is a non-existing namespace. i.e. openshift-operators must not be created
        create: false

      # Information about the subscription
      subscription:
        # Version that shall be used
        channel: *channel-pipelines
        # Automatic of manual approval to update the Operator
        # Default: Automatic
        approval: Automatic
        # The operator Name
        operatorName: openshift-pipelines-operator-rh
        # Source of the Operator
        source: redhat-operators
        # Source Namespace, typically openshift-marketplace
        sourceNamespace: openshift-marketplace
      # Crete an Operator group of not
      operatorgroup:
        create: false
        # Watch own namespace or not.
        # Only makes sense when operatorgroup is created
        # AllNamespaces InstallModeType not supported, cannot configure to watch all namespaces
        notownnamespace: true

    #######
    # Loki
    #######
    loki-operator:
      enabled: true
      namespace:
        name: openshift-operators-redhat
        create: true
      subscription:
        channel: *channel-loki
        approval: Automatic
        operatorName: loki-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true

    ####################
    # OpenShift Logging
    ####################
    openshift-logging:
      enabled: true
      namespace:
        name: openshift-logging
        create: true
      subscription:
        channel: *channel-logging
        approval: Automatic
        operatorName: cluster-logging
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: false

    ############
    # NetObserv
    ############
    netobserv-operator:
      enabled: true
      namespace:
        name: openshift-netobserv-operator
        create: true
      subscription:
        channel: *channel-netobserv
        approval: Automatic
        operatorName: netobserv-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true

    ############
    # Cert-Utils
    ############
    cert-utils-operator:
      enabled: true
      namespace:
        name: cert-utils-operator
        create: true
      subscription:
        channel: *channel-cert-utils
        approval: Automatic
        operatorName: cert-utils-operator
        source: community-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true

    ##############
    # Cert-Manager
    ##############
    openshift-cert-manager-operator:
      enabled: true
      namespace:
        name: cert-manager-operator
        create: true
      subscription:
        channel: *channel-cert-manager
        approval: Automatic
        operatorName: openshift-cert-manager-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: false

    ###############
    # Quay Registry
    ###############
    quay-operator:
      enabled: true
      namespace:
        name: openshift-operators
        create: false
      subscription:
        channel: *channel-quay
        approval: Automatic
        operatorName: quay-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false
        notownnamespace: true

    ######################
    # Open Data Foundation
    ######################
    odf-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-storage
        create: true
      subscription:
        channel: *channel-odf
        approval: Automatic
        operatorName: odf-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
