---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      kind: ClusterLogging
      name: instance
    patch: |-
      - op: replace
        path: /spec/logStore/elasticsearch/redundancyPolicy
        value: 'ZeroRedundancy'