{{- if .Values.config_monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: {{ .Values.config_monitoring.enable_user_workload }} 
{{- end }}