{{- with .Values.console.console_logo }}
{{ if eq ( .enabled | toString) "true" }}
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  customization:
    customLogoFile:
      key: {{ .image.name | default "console-custom-logo.png" }}
      name: {{ .name | default "custom-logo" }}
    {{- if .customProductName }}
    customProductName: {{ .customProductName }}
    {{- end }}
{{- end }}
{{- end }}
