{{- if .Values.etcd_encryption.enabled }}
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  encryption:
    type: aescbc
{{- end }}
