apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldap-secret
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: AgC6wZ9LhKhOsrXWJjv3+x59K5v4u5ikiT1OqHHBI6pB2+x2Q6BTCcqXdFYqwteuO3230KVTcedGBqZDW3m2llostRrXmSa3xddDOUe5j4iTRPwa4HbGlwthus23S1li7zDHLD5IX0R7OoShTrv27Z3K9yADbEok4tFqpbt4Y/K7aN7yCYA+geR82GK3McKDaeBKjMf+nknsT0mqM6YQeTcFbVJSemInWFMuapX+fBpaAcreg2WspuGD2cJ4kUgxtt5xR6Rt6LLKV7KVXB5YI1P0Bzb1WwoYpd7mcVanaV5/n+E4fOGSAz7oc620NaWVv4eZHU/wSJyjlF1wv4hRz1r8SH0RoqTapZeOQ2DIclA1IZ/3wYq8dYjrra+x4Qx3gCD6dAqjUAv53PIJdnUablRd9/x2GQwpVA4dAs1BsMIduLrhY5iDceU4KrOywpEgUlgT+WQu1GHckkJRyZS0ZXQP9oYDPXvE4sEsYqYDQNOp+TfCz1ebIvqhSb2O9No1GlGRM2GHz1FmiIdJVts/wVtdurJN0LjbXdDB6PmRDFDgB4Cd3zbZVQGPaPTy2zkqsFhQB0SwilOCxtrPE4cmN3/dqxcCWsx1u9g7EQ21i9wSrJGqpwWmwb0hSx4aSNVHiP0U8YCEaGySyqz8osKV0enLhoOwy6l3RBvbS+7jfIaeznOVikZ13uyj8IMYVYmFlP6kw+S3Vy2DHTC4u/swgdoJmfO8j7IixA9f
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ldap-secret
      namespace: openshift-config

