apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldap-secret
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: AgAMp+W9RcaYarQga3wpi7jdEcAGj81Ai7DPLozkt1Zriz0G/Pu/2okVBQ+P/Ya0WBO6U6oR0ioGPwngYCTcpLLO58P2R4sNLdlEiSLKH5b7k17GYTWfZtoxd0yl/qJI7A2BE6ggV8ZR5tDZ9PImnjdDh4VMG2xzWtQW8roZ6jK1Jb9MnN6AQhkLDL0TmUDRj+rt/7fAf4Eu5SWBNiVk3nZ/zWDZvfGyjihzO9uKny87T7TbgnuIX2egE9ThjLEtiQ76+lwDvo9qAZsRCaQ+7VRWWJFxq2j5HEr6TElkhi+kxOw/NH6a/QiUcyNVVBBMXhfo3tZqZnprp+IShMz8tjmmiUfvCwfHpdiUeyebwEWTvNLy2iyzJa+3m9oo8924G0E2O7HjZxHpFOL7Azc+3mN9NZyOKVwt4PxFYUs8xiCDJ4qFqEQLnWgtP296ohuq+FZpT7dlQEh0VxAqNhlnXTZN2GJMUAiALyFqzaTiulRPIYBVFeKgi7XCJUdaPzoxPYe//eQTzJWDHB017raBlwU+YbHa4sSybnHA2AiHHn5O6RyjYljngVmsqwksfFD7t3qQrspN7Z9DNu6/+AC9yOjisipx/zXX7imsEDu2TR6fnTV97KpXBPzMg6Nlp+uvPjqn5A52chvD5sduVIr2wNUw01RCC0bBE2Od08cDtz09HsHyawaj44E8SYOcrl2pzMD97lhLSn7Q33YhJrEe7OjZTnpe9pI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ldap-secret
      namespace: openshift-config

