---
quay_namespace: &namespace quay-enterprise

quay:
  enabled: true

  namespace:
    name: *namespace

  # Bucket that shall be created
  bucket:
    name: quay-bucket

    # Name of the storageclass
    # Default: openshift-storage.noobaa.io
    storageclass: openshift-storage.noobaa.io

    # Syncwave for bucketclaim creation. This should be done very early, but it depends on ODF.
    # Default: 2
    syncwave: 2
  
  create_config_secret:
    enabled: true
    syncwave: 3

quay-registry-setup:
  quay:
    enabled: true
    syncwave: 10

    namespace:
      create: true
      name: *namespace
      syncwave: 1

    components:
      clair:
        overrides:
          replicas: 1
      clairpostgres: {}
      objectstore:
        managed: "false"
      redis: {}
      hpa:
        managed: "false"
      route: {}
      mirror:
        managed: "false"
      monitoring: {}
      tls: {}
      postgres: {}
      quay:
        overrides:
          replicas: 1
  
    job_init_quay:
      enabled: false
      syncwave: 5
      serviceAccount: quay-initiator

# Install Quay Operator
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    quay-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-operators
        create: false
      subscription:
        channel: stable-3.9
        approval: Automatic
        operatorName: quay-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false
        notownnamespace: true

helper-status-checker:
  enabled: true

  # use the value of the currentCSV (packagemanifest) but WITHOUT the version !!
  operatorName: quay-operator

  # where operator is installed
  namespace:
    name: openshift-operators

  serviceAccount:
    create: true
    name: "sa-quay"
