{{- with .Values.console.console_logo }}
{{ if eq ( .enabled | toString) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name | default "custom-logo" }}
  namespace: openshift-config 
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
binaryData:
  {{ .image.name | default "console-custom-logo.png" }}: |-
    {{ $.Files.Get (printf "%s" .image.console_logo) | b64enc }}
{{- end }}
{{- end }}
