kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-event-listener-zf5mwt
  namespace: {{ .Values.demo_pipelines }}
spec:
  to:
    kind: Service
    name: el-event-listener
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
