---
# General values
#
mgmt-cluster: &mgmtcluster https://kubernetes.default.svc
repourl: &repourl 'https://github.com/tjungbauer/test-app-of-apps'
repobranch: &branch main

helper-argocd:

  general:
    source:
      repourl: *repourl
    branch: *branch
    server: *mgmtcluster

  # APPLICATIONS
  applications:

    wave-1-in-cluster:
      enabled: true
      syncwave: '1'
      description: "Wave 1 for local cluster"
      # namespace:
      #   name: openshift-gitops
      #   create: false
      # server: *mgmtcluster
      # project: default
      syncOptions:
        - name: ApplyOutOfSyncOnly
          value: true
      source:
        path: gitops-waves/waves/wave-0-loki-operator
        # repourl: 'https://github.com/tjungbauer/test-app-of-apps'
        # targetrevision: main

