apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
  labels:
    gitops.ownedBy: cluster-config
  name: configure-acs
spec:
  destination:
    namespace: <ACS NAMESPACE>
    server: <KUBERNETES CLUSTER>
  project: cluster-config
  source:
    path: <GITHUB PATH>
    repoURL: <GITHUB>
    targetRevision: <GITHUB TARGET VERSION>
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
  info:
    - name: Description
      value: 'Configure ACS ... This job will fail until the operator has been installed'