apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - install-advanced-cluster-security.yaml
  - configure-advanced-cluster-security.yaml

patches:
#  - patch: |-
#      - op: replace 
#        path: /spec/source/path
#        value: components/apps/operator-advanced-cluster-security/overlays/latest
#    target:
#      name: "install-acs-operator" 
#      kind: Application
  - patch: |-
      - op: replace 
        path: /spec/source/path
        values: clusters/management-cluster/config/acs-config/overlays
    target:
      name: "configure-acs"
      kind: Application
  - patch: |-
      - op: replace 
        path: /spec/destination/namespace
        value: stackrox
    target:
      kind: Application