---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/kustomize/console-customizations/console-banner/

# Modify the colors
patches:
- path: patch-console-banner.yaml
  target:
    group: console.openshift.io
    kind: ConsoleNotification
    name: consolebanner
    version: v1
