# Example


customer.name: customerA
customer.normalized: customera # name for ArgoCD must be in lower case
environment: in-cluster

helper-proj-onboarding:
  namespace:
    name: my_test_application
    enabled: true
    #gitops_namespace: gitops-applications
