# Example values files for a customer onboarding

# Name of the custoemrs. This must be the path.basename.
customer.name: customerA

# Normalized name of the customer. This must be LOWER case, otherwise ArgoCD will fail
customer.normalized: customera # name for ArgoCD must be in lower case

# Environment to which these values are valid
environment: in-cluster

# Parameters handed over to sub-chart helper-proj-onboarding
helper-proj-onboarding:

  # List of namespaces this customer shall have. Namespace configuration
  namespaces:

    # name of first namespace
    - name: customera-project-1

      # shall namespace be created of not
      enabled: true

    # name of second namespace
    - name: customera-project-2

      # shall namespace be created of not
      enabled: true