# Example


namex: customerA
name.normalized: customera # name for ArgoCD must be in lower case
cluster: 1
environment: in-cluster

helper-proj-onboarding:
  namespace:
    name: my_test_application
    enabled: true
    #gitops_namespace: gitops-applications
