apiVersion: flows.netobserv.io/v1alpha1
kind: FlowCollector
metadata:
  name: cluster
  namespace: network-observability
spec:
  agent: ebpf
  clusterNetworkOperator:
    namespace: openshift-network-operator
  consolePlugin:
    logLevel: info
    port: 9001
    register: true
    portNaming:
      enable: true
      portNames:
        '3100': loki
    imagePullPolicy: IfNotPresent
    image: 'quay.io/netobserv/network-observability-console-plugin:v0.1.4'
    replicas: 1
  ebpf:
    logLevel: info
    cacheMaxFlows: 1000
    imagePullPolicy: IfNotPresent
    excludeInterfaces:
      - lo
    cacheActiveTimeout: 5s
    interfaces: []
    image: 'quay.io/netobserv/netobserv-ebpf-agent:v0.1.2'
    sampling: 0
  flowlogsPipeline:
    logLevel: info
    port: 2055
    prometheusPort: 9102
    imagePullPolicy: IfNotPresent
    enableKubeProbes: true
    image: 'quay.io/netobserv/flowlogs-pipeline:v0.1.3'
    replicas: 1
    healthPort: 8080
    kind: DaemonSet
  ipfix:
    cacheActiveTimeout: 20s
    cacheMaxFlows: 400
    sampling: 400
  loki:
    timeout: 10s
    maxRetries: 10
    maxBackoff: 5m0s
    staticLabels:
      app: netobserv-flowcollector
    url: 'http://loki.network-observability.svc:3100/'
    batchWait: 1s
    minBackoff: 1s
    batchSize: 102400
  namespace: network-observability
