apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - enable-etcd-encryption.yaml

patches:
  - patch: |-
      - op: replace 
        path: /spec/source/path
        value: clusters/management-cluster/config/etcd-encryption/overlays
    target:
      kind: Application