apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  created-by: cluster-bootstrap
  author: 'Thomas_Jungbauer'
  clustername: 'Management_Cluster'

resources:
- ../../../../../components/clusterconfig/self-provisioner/base

patches:
  - patch: |-
      - op: replace 
        path: /metadata/annotations/rbac.authorization.kubernetes.io~1autoupdate
        value: false
    target:
      kind: ClusterRoleBinding
  # syncOption in argocd application must set
  #  syncOptions:
  #    - Replace=true
  - patch: |-
      - op: remove 
        path: /subjects
    target:
      kind: ClusterRoleBinding

