endpoint: &endpoint sonarqube.apps.ocp.aws.ispworld.at

namespace:
  name: sonarqube
  create: true

endpoint: *endpoint

# Sonarqube Settings
sonarqube:
  OpenShift:
    enabled: true
    createSCC: true
  persistence:
    enabled: true
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - name: *endpoint
        path: /
