namespace:
  name: sonarqube
  create: true

# Sonarqube Settings
sonarqube:
  OpenShift:
    enabled: true
  persistence:
    enabled: true
  networkPolicy:
    enabled: true
  ingress:
    enabled: true
    hosts:
      - name: sonarqube.apps.ocp.aws.ispworld.at
        path: /
