---
openshift-gitops:
  gitopsinstances:
    gitops_application:
      enabled: true
      namespace: gitops-application
      rbac:
        defaultPolicy: 'role:none'
        policy: |-
            # Access Controll
            g, system:cluster-admins, role:admin
            g, cluster-admins, role:admin
            p, role:none, applications, get, */*, deny
            p, role:none, certificates, get, *, deny
            p, role:none, clusters, get, *, deny
            p, role:none, repositories, get, *, deny
            p, role:none, projects, get, *, deny
            p, role:none, accounts, get, *, deny
            p, role:none, gpgkeys, get, *, deny

            # Adding Roles for specific group, i.e. Developers
            p, role:application-1-dev, applications, get, application-1/*, allow
            p, role:application-1-dev, clusters, get, https://kubernetes.default.svc, allow
            g, application-1-dev, role:application-1-dev
        scopes: '[groups]'
      resourceExclusions: |-
        # resources to be excluded
        - apiGroups:
          - tekton.dev
          clusters:
          - '*'
          kinds:
          - TaskRun
          - PipelineRun
