---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators-redhat

resources:
  - elasticsearch-namespace.yaml
  - elasticsearch-operatorgroup.yaml
  - elasticsearch-subscription.yaml
