api_endpoint: central-stackrox.apps.home.ocplab.com
# change if the UI is hosted on a different endpoint:
ui_endpoint: "{{ api_endpoint }}"

auth_provider: {name: OpenShift, type: openshift}
default_auth_provider_role: None

permission_sets:
  - name: Namespace Administrator
    description: A user that is an administrator of one or more namespaces across various clusters
    resourceToAccess:
      APIToken: NO_ACCESS
      Alert: READ_ACCESS
      AllComments: NO_ACCESS
      AuthProvider: NO_ACCESS
      BackupPlugins: NO_ACCESS
      CVE: NO_ACCESS
      Cluster: NO_ACCESS
      Compliance: NO_ACCESS
      ComplianceRunSchedule: NO_ACCESS
      ComplianceRuns: NO_ACCESS
      Config: NO_ACCESS
      DebugLogs: NO_ACCESS
      Deployment: READ_ACCESS
      Detection: READ_ACCESS
      Group: NO_ACCESS
      Image: READ_ACCESS
      ImageComponent: NO_ACCESS
      ImageIntegration: NO_ACCESS
      Indicator: READ_ACCESS
      K8sRole: READ_ACCESS
      K8sRoleBinding: READ_ACCESS
      K8sSubject: READ_ACCESS
      Licenses: NO_ACCESS
      Namespace: READ_ACCESS
      NetworkBaseline: READ_ACCESS
      NetworkGraph: READ_ACCESS
      NetworkGraphConfig: READ_ACCESS
      NetworkPolicy: READ_ACCESS
      Node: NO_ACCESS
      Notifier: NO_ACCESS
      Policy: READ_ACCESS
      ProbeUpload: NO_ACCESS
      ProcessWhitelist: NO_ACCESS
      Risk: READ_ACCESS
      Role: NO_ACCESS
      ScannerBundle: NO_ACCESS
      ScannerDefinitions: NO_ACCESS
      Secret: READ_ACCESS
      SensorUpgradeConfig: NO_ACCESS
      ServiceAccount: READ_ACCESS
      ServiceIdentity: NO_ACCESS
      User: NO_ACCESS
      WatchedImage: READ_WRITE_ACCESS

access_scopes:
  - name: namespace1
    description: Access rights for users that can manage their namespaces
    rules:
      includedClusters: []
      includedNamespaces:
      - clusterName: local-cluster
        namespaceName: namespace1
      clusterLabelSelectors: []
      namespaceLabelSelectors: []

roles:
  - name: Namespace1 Admins
    description: Administrators of namespace1
    permission_set: Namespace Administrator
    access_scope: namespace1
    global_access: NO_ACCESS

# Associate roles with users/groups in Provider
role_mappings:
  - key: name
    value: admin
    role_name: Admin
  - key: name
    value: "kube:admin"
    role_name: Admin
  - key: name
    value: opentlc-mgr
    role_name: Admin
  - key: groups
    value: namespace1
    role_name: Namespace1 Admins
