api_endpoint: central-stackrox.apps.home.ocplab.com
# change if the UI is hosted on a different endpoint:
ui_endpoint: "{{ api_endpoint }}"

auth_provider: {name: OpenShift, type: openshift}
default_auth_provider_role: None

permission_sets:
#  - name: Namespace Administrator
#    description: A user that is an administrator of one or more namespaces across various clusters
#    resourceToAccess:
#      Access: NO_ACCESS
#      Administration: NO_ACCESS
#      Alert: READ_ACCESS
#      CVE: READ_ACCESS
#      Cluster: READ_ACCESS
#      Compliance: NO_ACCESS
#      Deployment: READ_ACCESS
#      DeploymentExtension: READ_ACCESS
#      Detection: READ_ACCESS
#      Integration: NO_ACCESS
#      Image: READ_ACCESS
#      K8sRole: READ_ACCESS
#      K8sRoleBinding: READ_ACCESS
#      K8sSubject: READ_ACCESS
#      Namespace: READ_ACCESS
#      NetworkGraph: READ_ACCESS
#      NetworkPolicy: READ_ACCESS
#      Node: READ_ACCESS
#      Secret: READ_ACCESS
#      ServiceAccount: READ_ACCESS
#      WatchedImage: READ_WRITE_ACCESS
#      WorkflowAdministration: READ_ACCESS
#      VulnerabilityManagementRequests: READ_WRITE_ACCESS

#access_scopes:
#  - name: namespace1
#    description: Access rights for users that can manage the namespaces namespace1
#    rules:
#      includedClusters: []
#      includedNamespaces:
#      - clusterName: local-cluster
#        namespaceName: namespace1
#      clusterLabelSelectors: []
#      namespaceLabelSelectors: []
#  - name: group_backend
#    description: Access rights for users that can manage the namespace backend
#    rules:
#      includedClusters: []
#      includedNamespaces:
#      - clusterName: local-cluster
#        namespaceName: backend
#      clusterLabelSelectors: []
#      namespaceLabelSelectors: []
#  - name: group_frontend
#    description: Access rights for users that can manage the namespace frontend
#    rules:
#      includedClusters: []
#      includedNamespaces:
#      - clusterName: local-cluster
#        namespaceName: frontend
#      clusterLabelSelectors: []
#      namespaceLabelSelectors: []

#roles:
#  - name: Namespace1 Admins
#    description: Administrators of namespace1
#    permission_set: Namespace Administrator
#    access_scope: namespace1
#    global_access: NO_ACCESS
#  - name: NS backend Admins
#    description: Administrators of backend
#    permission_set: Namespace Administrator
#    access_scope: group_backend
#    global_access: NO_ACCESS
#  - name: NS frontend Admins
#    description: Administrators of frontend
#    permission_set: Namespace Administrator
#    access_scope: group_frontend
#    global_access: NO_ACCESS

# Associate roles with users/groups in Provider#
role_mappings:
#  - key: name
#    value: admin
#    role_name: Admin
#  - key: name
    value: "kube:admin"
    role_name: Admin
#  - key: name
#    value: opentlc-mgr
#    role_name: Admin
#  - key: groups
#    value: group_backend
#    role_name: NS backend Admins
#  - key: groups
#    value: namespace1
#    role_name: namespace1 Admins
#  - key: groups
#    value: group_frontend
#    role_name: NS frontend Admins
