---
# Example values files for a customer onboarding
# It is huge, especially the NetworkPolicy part ... however, you do not need to use everything. I tried to make it is configurable as possible.

# Name of the custoemrs. This must be the path.basename.
customer.name: my-main-app

# Normalized name of the customer. This must be LOWER case, otherwise ArgoCD will fail
customer.normalized: my-main-app # name for ArgoCD must be in lower case

# Environment to which these values are valid, this should be the cluster name as visible in ArgoCD
environment: in-cluster

# Parameters handed over to sub-chart helper-proj-onboarding
helper-proj-onboarding:

  # List of namespaces this customer shall have. Namespace configuration
  namespaces:

    # name of first namespace
    - name: customera-project-1

      # shall namespace be created of not
      enabled: false

      # Create a local group with Admin users and the required rolebinding
      # If other systems, like LDAP Group sync is used, you will probaably not need this.
      local_admin_group:
        enabled: false
        users:
          - user1
          - user2
