

applicationsets:
  application_1:
    enabled: true

    argocd_project_setup:
      dev_rollout:
        enabled: true
        name: application-1-dev
        destinations:
          - name: *mgmtclustername
            # namespace: application-1  # taking the key later in the chart template
            server: *mgmtcluster
        sourceRepos:
          - 'https://github.com/argoproj/argocd-example-apps'
        rbac:
          - name: developers
            description: "Group to developers to deploy on DEV environment"
            groups:
              - application-1-dev
            # Do not forget to add role to management-cluster/management-gitops
            policies:
              - 'p, proj:application-1-dev:developers, applications, get, application-1-dev/*, allow'
              - 'p, proj:application-1-dev:developers, applications, create, application-1-dev/*, allow'
              - 'p, proj:application-1-dev:developers, applications, update, application-1-dev/*, allow'
              - 'p, proj:application-1-dev:developers, applications, delete, application-1-dev/*, allow'
              - 'p, proj:application-1-dev:developers, applications, sync, application-1-dev/*, allow'
              - 'p, proj:application-1-dev:developers, applications, override, application-1-dev/*, allow'
          - name: production-rollout
            description: "Group for production deployment"
            groups:
              - application-1-ops
            # Do not forget to add role to management-cluster/management-gitops
            policies:
              - 'p, proj:application-1-dev:production-rollout, applications, get, application-1-dev/*, allow'
              - 'p, proj:application-1-dev:production-rollout, applications, create, application-1-dev/*, deny'
              - 'p, proj:application-1-dev:production-rollout, applications, update, application-1-dev/*, deny'
              - 'p, proj:application-1-dev:production-rollout, applications, delete, application-1-dev/*, deny'
              - 'p, proj:application-1-dev:production-rollout, applications, sync, application-1-dev/*, deny'
              - 'p, proj:application-1-dev:production-rollout, applications, override, application-1-dev/*, deny'

      prod_rollout:
        enabled: true
        name: application-1-prod
        destinations:
          - name: *prodclustername
            # namespace: application-1  # taking the key later in the chart template
            server: *prodcluster
        sourceRepos:
          - 'https://github.com/argoproj/argocd-example-apps'
        rbac:
          - name: production-rollout
            description: "Group for production deployment"
            groups:
              - application-1-ops
            # Do not forget to add role to management-cluster/management-gitops
            policies:
              - 'p, proj:application-1-prod:production-rollout, applications, get, application-1-prod/*, allow'
              - 'p, proj:application-1-prod:production-rollout, applications, create, application-1-prod/*, allow'
              - 'p, proj:application-1-prod:production-rollout, applications, update, application-1-prod/*, allow'
              - 'p, proj:application-1-prod:production-rollout, applications, delete, application-1-prod/*, allow'
              - 'p, proj:application-1-prod:production-rollout, applications, sync, application-1-prod/*, allow'
              - 'p, proj:application-1-prod:production-rollout, applications, override, application-1-prod/*, allow'

