apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  created-by: cluster-bootstrap
  author: 'Thomas_Jungbauer'
  clustername: 'Management_Cluster'
  
resources:
 - ../../../../../all/overlays/oauth-cluster-idp/htpasswd

patches:
  - patch: |-
      - op: replace 
        path: /spec/identityProviders/0/name
        value: htpasswd_provider
    target:
      kind: OAuth
      name: cluster