apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift

resources:
- rox-deployment-check-task.yaml
# Import original one, once PR by GNunn has been merged
#- https://raw.githubusercontent.com/stackrox/contributions/main/ci/Tekton/Tasks/rox-image-check-task.yml
- rox-image-check-task.yaml
- rox-image-scan-task.yaml