apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-object-manager
  labels:
    gitops.ownedBy: cluster-config
{{ include "common.labels" . | indent 4 }}
spec:
  destination:
    namespace: openshift-gitops
    server: {{ .Values.server }}
  project: {{ .Values.argocd_project }}
  source:
    path: {{ .Values.path }}
    repoURL: {{ .Values.repourl }}
    targetRevision:  {{ .Values.revision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  info:
    - name: Description
      value: 'This is the starting point which will initialize all applicationsets or argocd applications'
