apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  created-by: cluster-bootstrap
  author: 'Thomas_Jungbauer'
  clustername: 'Management_Cluster'

resources:
- ../../../../../components/apps/operator-elasticsearch/overlays/default

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: elasticsearch-operator
      namespace: openshift-operators-redhat
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-5.3'