{{- range $key, $value := .Values.additional_applications }}
{{ if eq ($value.enabled | toString) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '5'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    gitops.ownedBy: openshift-gitops
    {{- include "argo.labels" $ | nindent 4 }}
    {{- if $value.labels }}
    {{- range $key_labels, $value_labels := $value.labels }}
    {{ $key_labels }}: {{ $value_labels }}
    {{- end }}
    {{- end }}
  name: {{ $key | replace "_" "-" }}
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ .namespace.name }}
    server: {{ .server }}
  project: {{ .project }}
  {{- if eq (.namespace.create | toString) "true" }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  {{- end }}
  source:
    {{- if .path }}
    path: {{.path }}
    {{- else }}
    chart: {{ .chartname }}
    {{- end }}
    {{- if .helm }}
    helm:
      parameters:
    {{- range .helm.helmvalues }}
        - name: {{ .name }}
          value: '{{ .value }}' 
    {{- end }}
    {{- end }}
    repoURL: {{ .source.repourl }}
    targetRevision: {{ .source.targetrevision }}
  info:
    - name: Description
      value: {{ .description | default "No Description" }}
{{- end }}
{{- end }}
