{{- with .Values.etcd_encryption }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .appsetname }}
  namespace: openshift-gitops
spec:
  generators:
  {{- if .clusterlist }}
    {{- range .clusterlist }}
      - clusters:
          selector:
            matchLabels:
              env: {{ .env }}
    {{- end }}
  {{- else }}
    - clusters: {}
  {{- end }}  
  template:
    metadata:
      name: >-
          {{ printf "{{ name }}-%s" .appsetname}}
    spec:
{{- end }}
{{- with .Values.general }}
      #project: {{ .argocd_project }}
      project: >-
        {{ printf "{{ name }}" }}
      source:
        repoURL: {{ .source.repourl }}
        targetRevision: {{ .branch }}
{{- end }}
{{- with .Values.etcd_encryption }}
        path: {{ .path }}
      syncPolicy:
        automated:
          prune: {{ .syncpolicy_prune | default "false"  }}
          selfHeal: {{ .syncpolicy_selfheal | default "false"  }}
      destination:
        server:  >-
          {{ printf "{{ server }}" }}
        namespace: default
{{- end }}
