{{- with .Values.install_quay }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .appsetname }}
  namespace: openshift-gitops
spec:
  generators:
  {{- if .generatorlist }}
    - list:
        elements: 
        {{- range .generatorlist }}
          - cluster: {{ .clustername }}
            url: {{ .clusterurl }}
        {{- end }}
  {{- end }}
# This does not work, since openshift-gitops keeps removing the label of the local ArgoCD secret
#  {{- if .generatorclusters }}
#    {{- range .clusters }}
#      - clusters:
#          selector:
#            matchLabels:
#              env: {{ .env }}
#    {{- end }}
#  {{- else }}
#    - clusters: {}
#  {{- end }}
  template:
    metadata:
      name: >-
          {{ printf "{{ cluster }}-%s" .appsetname}}
    spec:
{{- end }}
{{- with .Values.general }}
      project: {{ .argocd_project }}
      source:
        repoURL: {{ .source.repourl }}
        targetRevision: {{ .branch }}
{{- end }}
{{- with .Values.install_quay }}
        path: {{ .path }}
      syncPolicy:
        automated:
          prune: {{ .syncpolicy_prune | default "false"  }}
          selfHeal: {{ .syncpolicy_selfheal | default "false"  }}
      destination:
        server:  >-
          {{ printf "{{ url }}" }}
        namespace: default
{{- end }}
