{{- range $key, $value := .Values.applicationsets }}
{{ if eq ($value.enabled | toString) "true" }}
{{ if eq ($value.group_dev.enabled | toString) "true" }}
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: {{ if .group_dev.name }}{{ .group_dev.name }}{{- else }}{{ $key | replace "_" "-" }}-dev{{- end }}
users:
  {{- range .group_dev.users }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}