{{- range $key, $value := .Values.applicationsets }}
{{ if eq ($value.enabled | toString) "true" }}
{{ if eq ($value.group_ops.enabled | toString) "true" }}
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: {{ if .group_ops.name }}{{ .group_ops.name }}{{- else }}{{ $key | replace "_" "-" }}-ops{{- end }}
users:
  {{- range .group_ops.users }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}