apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: {{ .Values.rhacs_clustername }}
  namespace: {{ .Values.rhacs_namespace }}
spec:
  clusterName: {{ .Values.rhacs_clustername }}
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
