apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: <RESOURCE LOCKER NAME>
spec:
  patches:
    - id: <RESOURCE-LOCKER-NAME>
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/infra: ''
            environment: dev
      patchType: application/strategic-merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: <NODE NAME>
  serviceAccountRef:
    name: node-patcher

### EXAMPLE 
#apiVersion: redhatcop.redhat.io/v1alpha1
#kind: ResourceLocker
#metadata:
#  name: set-node-labels
#spec:
#  patches:
#    - id: set-node-role
#      patchTemplate: |
#        metadata:
#          labels:
#            node-role.kubernetes.io/infra: ''
#            environment: dev
#      patchType: application/strategic-merge-patch+json
#      targetObjectRef:
#        apiVersion: v1
#        kind: Node
#        name: ip-10-0-157-38.us-east-2.compute.internal
#  serviceAccountRef:
#    name: node-patcher