apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../all
- ../../../../../components/clusterconfig/init_openshift_logging/overlays/default

patches:
  - target:
      kind: ClusterLogging
      name: instance
    patch: |-
      - op: replace
        path: /spec/logStore/elasticsearch/storage/storageClassName
        value: 'gp2'