apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logging-loki-s3
  namespace: openshift-logging
spec:
  encryptedData:
    lokistack-s3-secret.yaml: AgBJ3ZCrjrsGKBZypUkQy49WJezrJvlbcID4dWrUY/N+Trm0Mx07gbzF5MxWrCG4iBVS2R4XrZIitJkeqSye/lCXP4C9l55SKlQ8NQ3LuIodiINyrP7U/AcJxBTScdPpvfnbxjQzid0f1vrQN8S/kbkgiqcjbtTjgj5x9EP+wiRwnK4NBZSH2ZW0bz9CQAwiuV0a5/iw4na3GkcOHXqCiGcwZGcuBDSEPTvXSoE9b9d6Ofmk6aKTwdORqlYEAzYiKraSftdY0Gb2ZeAAtOcWx2TF2F5+lcmIvmEygIFvkDMFGo5IaqkvDBz097v1pVpqX8+4wy/UhIxyXFXeDRakwgZ2us9fdlN3Ec4oyVPNA3ADx50RmZqcg9d1/QTWBnFqu58NFguOoFM71N4hAgm5GDzcxIBRTRN1UcHkRsH70D5XKDkLu5M+wu4qrZaeuztDo2GvqKwCETiArJUjTdP8A1YMNdhXwusYtCfGSVPlfxOkQGijPOURBTwQGQayqLeACVIIOqeKPUY3wt3cQBpuekDjYQ3mPXrhMw1BSy6pCX+fsh2vd2Vcl/hUcXwfeE8PTN/3WP+HjNOJJSupZ1LTLi8gcg7pHkFeUg8ImSiwbG9jIgDFOolEk5yGRm2w8EHZ3S6qbQaJ3wVZNH+ZZ+Z2Gv7hSq+Q91rzjrtXUWz/VyuFQu+iRWd4JOUWF7kP0rJ5axpD+6NuBinmBeHNT/JRYugAkJ+FWjKJAJBxtPBXRtpjBR6irGcLWkPa8OxUzyjM3k8c/RX6UXkvrpdwuxfXHZal+/HcoTUT4QDpPsvxPn/cQgQr6ZqMOBZ7x7/oMbLFNHr0EiUZQYMGORPE1CbjNC+GOOvMDcbMrNXshV6+b79Ep2ODVLrNX86RQ5S7PecVQwZD6lso6kCqyrvqTx4waB2fI3/lXWVniLfoTIk6vR8d8f3Ndwp3GU9bZo3LrfnSy9vwLVBYOSH8vBotQDCE5kJ7l/X1TPLuLnxms1zwOtR9nADGgCbBVDPPQtbrLtcmv7KdVZINXaSur0HsocZ29UvC6UXDGumHoMz0O9d8rve8AUuRLoEFISlFGtzZUvCMyvVwA4mDeyPKs6W0skCXrXeJj77qD4NRaoibPnM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: logging-loki-s3
      namespace: openshift-logging

