apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logging-loki-s3
  namespace: openshift-logging
spec:
  encryptedData:
    lokistack-s3-secret.yaml: AgDkbyLtjeEqok6ZlVF9JGdsZifY/aFAzJvcvfiSGYeW1xoopkgI+V2z17FJ0un/XI2Q2k6NhJMcnlGdL1TYenwKXF5VNeOM3ZHAqFeGroBeovBfXb2up3xlEuSnTLYBMyMqWAoNVuVmEJcuh3usORR3zL3Ut9NAVzk7uoWZ6LuBptv/cQ8oKjmfWaU7C/GB7tEId3jmrh3fESesvJA9CmWSzeWrgytC6gA5jZ7ld1Bpn624IL54pe9LUY+WuWQlqwdRyJwfq7ytug0G7WuYj6gXRjXLVrwM2tphSvny/o2B1zwP6JtYAuCpAgwjt20gl5Dt4SbC4mxvmXVYisOGgJKxJJTuGNuKI9F4SbVFwhLOte0fMQjQpF+INirDssJyu3ATlvjUoX8ctfu4OryPR17uj59XURILsXTGbzwlFCrH6OYkivvX8TCY0sZWcqk94LTwC0Wwd4+6DpkRBVJ6Xa5wycGX/CIK7SvtV2eAdT25yUk++mzNzdqW+G0RsSHEE9O7P3/ZYID4IJTaqkAvXhRqvMrZPqPBAfkaODV6iYror+ZVgzg1Ycc6tAugw7VhzsO67wg57H2gsnQBt4f0xlo5cq4abJ9zUen5MbygDlkTiJZwwqjNSah1pL5ke2xPlgTXXDXe5dKSOTvYpdLCXKkQD5RLxy8h/g8KQRxPnKJ9bC7D39WsvsPWznpX1ILnTjnGmlTZbhCMtceZZrICgRuSE2ts6l+RophYprxxnFk4g7xArZ5rH3TG1Nv42CgS3GYJcflwjVsXFjYajwddzJI2p8jnwWMzMFo8d/onHnRz1/3I27Oa1fojqySp/c1Hu2WkV8KaQwWrb/wYCVACL4Lzy0EGmz+Y5hJtKaRROgCjcCtsIcBrWcfeHlfssep4DFihX8jw+bWlv0OdDRahcI55CYM32nR7dh1qcC8al0VUT3GOUhZn4FLXLF3P9ys/vNqBEHHNyWoSSsT6FBgATyA5LAGnCsG3JW5umIvNXhSJy5k4f7Nhitp+Qzcr8xS4Y6nfjTiLCmwAjlzLnEbdwt1NVls94WPXlWy2ag3OY0+ysyHPGmp2nmAPxpwxQWdY3BrO2w7jfO61pHV1F+r3VPFEbk+rj+vQ0uW3Xk8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: logging-loki-s3
      namespace: openshift-logging

