apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disable-self-provisioner.yaml

patches:
  - patch: |-
      - op: replace 
        path: /spec/source/path
        value: clusters/management-cluster/config/self-provisioner/overlays
    target:
      kind: Application