apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  created-by: cluster-bootstrap
  author: 'Thomas_Jungbauer'
  clustername: 'Management_Cluster'
  
resources:
- ../../../../../components/clusterconfig/init_advanced_cluster/overlays/default


