apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../all
- ../../../../../components/clusterconfig/config_advanced_cluster_operator/base
- ../../../../../components/clusterconfig/console-banner/base


