# General values
#

etcd_encryption: 
  appsetname: enable-etcd-encryption
  path: clusters/all/clusterconfig/enable-etcd-encryption 

install_advanced_cluster_security:
  appsetname: install-rhacs
  path: components/operators/advanced_cluster_security/overlays/latest
  environment: management

general:
  argocd_project: 'default'
  source: 
    repourl: 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
  branch: main

