# General values
#

# Set cluster names ... Unfortunately the openshift-gitops operator keeps removing the secret of the in-cluster (local cluster), therefor we switch ti list generator
# https://issues.redhat.com/browse/GITOPS-1777
mgmt-cluster:  &mgmtcluster https://kubernetes.default.svc
production-cluster: &prodcluster https://api.ocp.ispworld.at:6443
main_repourl: &mainrepourl 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
main_repobranch: &mainbranch main

etcd_encryption: 
  appsetname: enable-etcd-encryption
  path: clusters/all/clusterconfig/enable-etcd-encryption 
  generatorclusters: []

install_advanced_cluster_security:
  appsetname: install-rhacs
  path: components/operators/advanced_cluster_security/overlays/latest
  generatorlist:
    - clustername:  management
      clusterurl: *mgmtcluster
    - clustername:  production
      clusterurl: *prodcluster
  syncpolicy_prune: true
  syncpolicy_selfheal: true

init_rhacs_central:
  appname: in-cluster-init-rhacs-central
  server: *mgmtcluster
  project: default 
  source: 
    path:  clusters/management-cluster/init_advanced_cluster_security/
    repourl: *mainrepourl
    targetrevision: *mainbranch  

install_quay:
  appsetname: install-quay
  path: components/operators/redhat-quay/overlays/stable
  generatorlist:
    - clustername:  management
      clusterurl: *mgmtcluster
  syncpolicy_prune: false
  syncpolicy_selfheal: false

general:
  argocd_project: 'default'
  source: 
    repourl: *mainrepourl
  branch: *mainbranch 



