apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  created-by: cluster-bootstrap
  author: "Thomas_Jungbauer"

resources:
  - ../base/kustomization.yaml
  - console-banner-app.yaml

patches:
  - patch: |-
      - op: replace 
        path: /spec/destination/server
        value: https://kubernetes.default.svc
    target:
      kind: Application
  - patch: |-
      - op: replace 
        path: /spec/source/path
        value: clusters/management-cluster/overlays
    target:
      kind: Application
  - patch: |-
      - op: replace 
        path: /spec/source/targetRevision
        value: main
    target:
      kind: Application
  - patch: |-
      - op: replace 
        path: /spec/source/repoURL
        value: https://github.com/tjungbauer/openshift-cluster-bootstrap
    target:
      kind: Application
