{{- range $key, $value := .Values.nodes }}
---
kind: Node
apiVersion: v1
metadata:
  name: {{ $value.name | quote }}
  labels:
    {{- range $key_label, $value_label := $value.labels }}
{{ indent 4 $key_label }}: {{ $value_label }}
    {{- end }}
{{- end }}
