apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-manager
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: <KUBERNETES CLUSTER>
  project: <ARGOCD PROJECT>
  source:
    path: <GITHUB PATH>
    repoURL: <GITHUB>
    targetRevision: <GITHUB TARGET VERSION>
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  info:
    - name: Description
      value: 'This is the starting point for the cluster configuration, it automatically manages the deployment of initial operators, authentication, etcd encryption ...'
