{{- range $key, $value := .Values.argocd_projects }}
{{ if eq ($value.enabled | toString) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: {{ $key }}
  namespace: gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---
{{- end }}
{{- end }}