{{- range $key, $value := .Values.namespaces }}
{{ if eq ($value.enabled | toString) "true" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ $.Values.prefix }}-{{- if ne $.Values.prefix "" }}{{- else }}{{ end }}{{ $key | replace "_" "-" }}"
  labels:
    openshift.io/cluster-monitoring: "true"
{{- end }}
{{- end }}
