policyGenerator:
  policyDefaults:
    disabled: false
    policyname: console-banner
    namespace: policies-hub
    categories:
      - CM Configuration Management
    controls:
      - CM Console Customizations
    remediationAction: inform

placement:
  clusterSets:
    - hub
  lableSelectors:
    - key: name
      operator: In
      values:
        - local-cluster

policySet:
  enabled: false
  sets:
    - name: console-customizations
      description: "Contains console customizations"
      policies:
        - console-banner
