---
generic-cluster-config:
  workload_monitoring:
    enabled: true

  idp:
    enabled: true
    customloginpage:
      enabled: true
      secretname: matrix-login-template
      secretname_providerpage: matrix-provider-template
    enable_idp_provider: true
    providers:
      htpasswd:
        - name: HTPASSWD
          enabled: true
      ldap:
        - name: LDAP
          enabled: false
          url: 127.0.0.1
          insecure: true
          binddn: xyz
          secretname: ldap-secret
          cmname: ca-config-map
          preferredusername: sAMAccountName
