---
generic-cluster-config:
  console_banner:
    enabled: true
    text: 'MGMT Cluster'
    location: BannerTop
    color: "#FFFFFF"
    backgroundcolor: '#0088ee'

  workload_monitoring:
    enabled: true

  idp:
    enabled: true
    providers:
      htpasswd:
        - name: HTPASSWD
          enabled: true
      ldap:
        - name: LDAP
          enabled: false
          url: 127.0.0.1
          insecure: true
          binddn: xyz
          preferredusername: sAMAccountName
