---

---
# This must be defined here, since you cannot hand over a .File to a subchart
console:
  console_logo:
    enabled: true
    image:
      name: console-custom-logo.png
      console_logo: images/custom-logo.png
    name: console-custom-logo

generic-cluster-config:
  console:
    console_banners:
      topbanner:
        enabled: true
        text: 'MGMT Cluster'
        location: BannerTop
        color: "#FFFFFF"
        backgroundcolor: '#0088ee'
      bottombanner:
        enabled: true
        text: Copyright © 2020 Sample Company, Inc. |
        location: BannerBottom
        color: "#FFFFFF"
        backgroundcolor: '#000'
        link:
          href: 'https://www.example.com/data-protection-policy'
          text: Data Protection and Privacy Policy

    console_links:
      userlink:
        enabled: true
        text: "Intranet"
        location: UserMenu
        href: https://intranet
      namespacedlink:
        enabled: true
        text: Link valid for selected namespace only
        location: NamespaceDashboard
        href: https://report
        namespaces:
          - default
          - openshift-gitops
      namespacedlink_all_namespaces:
        enabled: true
        text: Report Violations
        location: NamespaceDashboard
        href: https://report
      helplink:
        enabled: true
        text: Red Hat CVE Database
        location: HelpMenu
        href: https://access.redhat.com/security/security-updates/#/cve
      applicationlink:
        enabled: true
        text: Red Hat Subscription Management
        location: ApplicationMenu
        href: https://access.redhat.com/management
        applicationMenu:
          section: My Subscriptions
          imageURL: https://raw.githubusercontent.com/tjungbauer/helm-charts/gh-pages/images/configuration.png

    yamlsamples:
      secret-yaml-sample:
        enabled: true
        targetResource:
          apiv: "v1"
          kind: Secret
        title: "Secret based on cleartext values"
        descr: "This is an example to create a Secret based on clear-text values"
        yamlDef: |+
              apiVersion: v1
              kind: Secret
              metadata:
                name: example
              type: Opaque
              stringData:
                email: youremail@address.com
                password: YourSuperPassword

  workload_monitoring:
    enabled: true

  idp:
    enabled: true
    providers:
      htpasswd:
        - name: HTPASSWD
          enabled: true
      ldap:
        - name: LDAP
          enabled: false
          url: 127.0.0.1
          insecure: true
          binddn: xyz
          secretname: ldap-secret
          cmname: ca-config-map
          preferredusername: sAMAccountName
