---
generic-cluster-config:
  console_banner:
    enabled: true
    text: 'MGMT Cluster'
    location: BannerTop
    color: "#FFFFFF"
    backgroundcolor: '#0088ee'

  workload_monitoring:
    enabled: true

  idp:
    enabled: true
    ldap:
      enabled: false
      name: LDAP
      url: 127.0.0.1
      insecure: true
      binddn: xyz
      preferredusername: sAMAccountName
    htpasswd:
      enabled: true
      name: HTPASSWD