apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: Red Hat Advanced Cluster Security
    openshift.io/node-selector: ''
  name: namespace: {{ .Values.rhacs_namespace }}
