---
# General values
#
# Set cluster names ...
# https://issues.redhat.com/browse/GITOPS-1777
# The issue that the in-cluster cannot be renamed has been resolved
mgmt-cluster: &mgmtcluster https://kubernetes.default.svc
mgmt-cluster-name: &mgmtclustername in-cluster
production-cluster: &prodcluster https://api.ocp.ispworld.at:6443
production-cluster-name: &prodclustername prod

repourl: &repourl 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
repobranch: &branch main

helper-argocd:
  argocd_projects:
    - *mgmtclustername
    - *prodclustername

  applicationsets:
    generic_clusterconfig:
      enabled: true
      description: "Deploy generic cluster configuration or etcd encryption"
      labels:
        category: cluster-configuration
      path: clusters/all/clusterconfig/
      # If Applications gets deleted, keep the resources
      # https://argocd-applicationset.readthedocs.io/en/stable/Application-Deletion/
      # preserveResourcesOnDeletion: true
      helm:
        per_cluster_helm_values: true
      generatorclusters: []
  #    repourl: "" # Optional
  #    targetrevision: "" # Optional

    aws-s3-controller:
      enabled: true
      description: "Deploy AWS S3 Controller"
      labels:
        category: cluster-configuration
      path: clusters/all/aws-controller-s3/
      helm:
        per_cluster_helm_values: true
      generatorclusters: []

    branding:
      enabled: true
      description: "Deploy Cluster Branding"
      labels:
        category: cluster-configuration
      path: clusters/all/clusterbranding/
      helm:
        per_cluster_helm_values: true
      generatorclusters: []

    etcd-encryption:
      enabled: true
      description: "Enable Cluster ETCD Encryption"
      labels:
        category: security
      path: clusters/all/etcd-encryption/
      helm:
        per_cluster_helm_values: false
      generatorclusters: []

    # Installs an App-of-Apps for Application onboarding
    application_onboarding:
      enabled: true
      description: "Deploy the application onboarding manager. This is the App-of-Apps which takes care of namespace creation"
      labels:
        category: project
      path: clusters/argocd-onboarding-manager
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false  # should be disabled for operators

    install_netobserv:
      enabled: true
      description: "Deploy the Net Observer Operator"
      labels:
        category: operators
      path: clusters/all/network_observer
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false

    # Additional instances of GitOps, usually used for applications deployments
    install_application_gitops:
      enabled: true
      description: "Deploy a 2nd GitOps instance for application deployments"
      labels:
        category: project
      path: clusters/management-cluster/management-gitops
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false

    # Install Sonarqube
    install_sonarqube:
      enabled: true
      description: "Install Sonarqube"
      namespace: sonarqube
      helm:
        releasename: sonarqube
      labels:
        category: project
      path: clusters/management-cluster/sonarqube
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false

    install_cyclonedx:
      enabled: true
      description: "Install CycloneDX SBOM Repository"
      namespace: cyclonedx
      labels:
        catagory: security
      path: clusters/management-cluster/cyclonedx
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false

    # A Collection of operators which will be deployed on ALL clusters.
    install-operator-collection:
      enabled: true
      description: "Deploy a collection of most useful Operators"
      labels:
        category: operators
      path: charts/collection-operators
      generatorclusters: []
      syncPolicy:
        autosync_enabled: false  # should be disabled for operators
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # A collection of MANAGEMENT operators,
    # installed usually on the management cluster only.
    install-mgmt-operator-collection:
      enabled: false
      description: "Deploy a collection of Operators which are usually installed on a management cluster only"
      labels:
        category: operators
      path: charts/collection-management-operators
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false  # should be disabled for operators
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # A Collection of OPTIONAL operators which will be deployed on ALL clusters.
    install_optional_operator_collection:
      enabled: false
      description: "Install optional Operators which might be good to test"
      labels:
        category: operators
      path: charts/collection-optional-operators
      generatorclusters: []
      syncPolicy:
        autosync_enabled: false  # should be disabled for operators
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # Compliance Scans should happen on ALL clusters
    install_compliance_scans:
      enabled: true
      description: "Deploy and configure the Compliance Scan Operator"
      labels:
        category: security
        solution: compliance
      path: charts/compliance-operator-full-stack
      generatorclusters: []
      syncPolicy:
        autosync_enabled: false  # should be disabled for operators
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # Install Container Security Operator
    install_container_security_operator:
      enabled: true
      description: "Deploy Container Security Operator"
      labels:
        category: security
      path: charts/setup-container-security-operator
      generatorclusters: []
      syncPolicy:
        autosync_enabled: false  # should be disabled for operators
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # Install OpenShift Logging
    install-openshift-logging:
      enabled: true
      description: "Deploy and Configure OpenShift Logging"
      labels:
        category: logging
      helm:
        per_cluster_helm_values: true
      path: clusters/all/clusterLogging
      # omitClustername: true
      generatorclusters: []
      syncPolicy:
        autosync_enabled: false

    # Configure Allowed Registries
    configure-allowed-registries:
      enabled: true
      description: "Configure Registries which are allowed"
      labels:
        category: security
      helm:
        per_cluster_helm_values: true
      path: clusters/all/allowed_registries
      # omitClustername: true
      generatorclusters: []
      syncPolicy:
        autosync_enabled: false

    # Install Vault-Config-Operator
    install-vault-config-operator:
      enabled: true
      description: "Deploy and Configure Vault-Config-Operator"
      labels:
        category: security
        solution: vault
      helm:
        per_cluster_helm_values: false
      path: clusters/management-cluster/vault-config
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false
      targetrevision: "main"

    # Install Cert-Manager and Cert-Utils Operators
    install-certificate-management:
      enabled: true
      description: "Deploy cert-manager and cert-utils operators"
      labels:
        category: security
      helm:
        per_cluster_helm_values: true
      path: clusters/all/cert-manager
      generatorlist: []
      syncPolicy:
        autosync_enabled: false
      targetrevision: "main"

    # init ACM
    init-rhacm:
      enabled: true
      description: "Initialize and deploy Red Hat Advanced Cluster Management"
      labels:
        category: security
        solution: rhacm
      helm:
        per_cluster_helm_values: false
      path: charts/rhacm-full-stack
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # Install ACS
    init-rhacs:
      enabled: true
      description: "Initialize Red Hat Advanced Cluster Security and deploy Central and SecuredCluster"
      labels:
        category: security
        solution: rhacs
      helm:
        per_cluster_helm_values: false
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false
      path: charts/rhacs-full-stack
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # Install RHACS Demo
    rhacs-demo-app:
      enabled: true
      description: "Deploy a vulnerable demo application to show results in RHACS"
      labels:
        category: security
        solution: rhacs
      helm:
        per_cluster_helm_values: false
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false
      path: charts/rhacs-demo-applications/
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # Install Pipeline Demo
    pipeline-demo:
      enabled: true
      description: "Deploy a demo pipeline about linting to show possibilities"
      labels:
        category: cicd
      helm:
        per_cluster_helm_values: false
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false
      path: charts/pipeline-example/
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    # Install ODF
    odf:
      enabled: true
      description: "Deploy Open Data Foundation Operator"
      labels:
        category: storage
      helm:
        per_cluster_helm_values: false
      generatorlist:
        - clustername: *mgmtclustername
          clusterurl: *mgmtcluster
      syncPolicy:
        autosync_enabled: false
      path: charts/openshift-data-foundation
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

    install_kyverno:
      enabled: true
      description: "Deploy Kyverno"
      namespace: kyverno
      labels:
        category: security
      chartname: kyverno
      helm:
        per_cluster_helm_values: false
        releasename: kyverno-policies
        helmvalues:
          - name: securityContext
            value: null
          - name: replicaCount
            value: 3
      syncPolicy:
        autosync_enabled: false
        # syncpolicy_prune: false
        # syncpolicy_selfheal: false
        syncOptions:
          - name: CreateNamespace
            value: true
          - name: ServerSideApply
            value: true
          - name: Replace
            value: true
      generatorclusters: []
      repourl: https://kyverno.github.io/kyverno
      targetrevision: "2.6.1"

    sealed-secrets:
      enabled: true
      description: "Deploy Sealed-Secrets"
      labels:
        category: security
      generatorlist: []
      project: default
      chartname: sealed-secrets
      helm:
        releasename: sealed-secrets
        helmvalues:
          - name: sealed-secrets.enabled
            value: 'true'
      syncPolicy:
        autosync_enabled: false
        syncpolicy_prune: false
        syncpolicy_selfheal: true
      generatorclusters: []
      repourl: "https://charts.stderr.at/"
      targetrevision: 1.0.11

  # APPLICATIONS
  applications:
    in-cluster-bulk-test:
      enabled: true
      server: *mgmtcluster
      namespace: {}
      project: default
      description: "Testing bulk operations"
      labels:
        category: test
      source:
        path: clusters/management-cluster/bulk-test

    hashicorp-vault:
      enabled: true
      description: "Deploy HashoCorp Vault"
      labels:
        category: security
      namespace:
        name: vault
        create: true
      server: *mgmtcluster
      project: default
      source:
        chartname: vault
        helm:
          releasename: vault
          helmvalues:
            - name: global.openshift
              value: 'true'
            - name: server.ha.raft.enabled
              value: 'true'
            - name: server.ha.enabled
              value: 'true'
            - name: server.ha.replicas
              value: '1'
        repourl: "https://helm.releases.hashicorp.com"
        targetrevision: 0.21.0

    node-labelling:
      enabled: true
      description: "Deploy Node Labels"
      labels:
        category: configuration
      namespace:
        name: default
        create: false
      server: *mgmtcluster
      project: default
      syncOptions:
        - name: ServerSideApply
          value: true
        - name: Validate
          value: false
      source:
        path: clusters/management-cluster/node-labels
        helm:
          valuesfiles:
            - name: values.yaml
        repourl: *repourl
        targetrevision: *branch

  # These define the default values.
  # It is possible to overwrite repourl and targetrevision in the Applications(Sets)
  general:
    argocd_project: 'default'
    source:
      repourl: *repourl
    branch: *branch
