# General values
#

# Set cluster names ... Unfortunately the openshift-gitops operator keeps removing the secret of the in-cluster (local cluster), therefor we switch ti list generator
# https://issues.redhat.com/browse/GITOPS-1777
mgmt-cluster: &mgmtcluster https://kubernetes.default.svc
production-cluster: &prodcluster https://api.ocp.ispworld.at:6443
main_repourl: &mainrepourl 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
main_repobranch: &mainbranch main

etcd_encryption: 
  appsetname: enable-etcd-encryption
  path: clusters/all/clusterconfig/enable-etcd-encryption 
  generatorclusters: []

install_advanced_cluster_security:
  appsetname: install-rhacs
  path: components/operators/advanced_cluster_security/overlays/latest
  generatorlist:
    - clustername:  in-cluster
      clusterurl: *mgmtcluster
    - clustername:  prod
      clusterurl: *prodcluster
  syncpolicy_prune: true
  syncpolicy_selfheal: true

init_rhacs_central:
  appname: in-cluster-init-rhacs-central
  server: *mgmtcluster
  project: default 
  source: 
    path:  clusters/management-cluster/init_advanced_cluster_security/
    repourl: *mainrepourl
    targetrevision: *mainbranch  

install_quay:
  appsetname: install-quay
  path: components/operators/redhat-quay/overlays/stable
  generatorlist:
    - clustername:  in-cluster
      clusterurl: *mgmtcluster
  syncpolicy_prune: false
  syncpolicy_selfheal: false

install_openshift_logging:
  appsetname: openshift-logging
  path: components/operators/openshift-logging/overlays/stable
  generatorclusters: []

install_openshift_servicemesh:
  appsetname: install-servicemesh
  path: components/operators/openshift-servicemesh/overlays/stable
  generatorlist:
    - clustername:  in-cluster
      clusterurl: *mgmtcluster
    - clustername:  prod
      clusterurl: *prodcluster
  syncpolicy_prune: true
  syncpolicy_selfheal: true

install_openshift_tracing:
  appsetname: install-jaeger
  path: components/operators/tracing-operator/overlays/stable
  generatorlist:
    - clustername:  in-cluster
      clusterurl: *mgmtcluster
    - clustername:  prod
      clusterurl: *prodcluster
  syncpolicy_prune: true
  syncpolicy_selfheal: true

install_kiali:
  appsetname: install-kiali
  path: components/operators/operator-kiali/overlays/stable
  generatorlist:
    - clustername:  in-cluster
      clusterurl: *mgmtcluster
    - clustername:  prod
      clusterurl: *prodcluster
  syncpolicy_prune: true
  syncpolicy_selfheal: true

install_elasticsearch:
  appsetname: install-elasticsearch
  path: components/operators/openshift-elasticsearch/overlays/default
  generatorlist:
    - clustername:  in-cluster
      clusterurl: *mgmtcluster
  syncpolicy_prune: true
  syncpolicy_selfheal: true

general:
  argocd_project: 'default'
  source: 
    repourl: *mainrepourl
  branch: *mainbranch 



