# General values
#

# Set cluster names ... Unfortunately the openshift-gitops operator keeps removing the secret of the *mgmtclustername (local cluster), therefor we switch ti list generator
# https://issues.redhat.com/browse/GITOPS-1777
mgmt-cluster: &mgmtcluster https://kubernetes.default.svc
mgmt-cluster-name: &mgmtclustername in-cluster
production-cluster: &prodcluster https://api.ocp.ispworld.at:6443
production-cluster-name: &prodclustername prod

main_repourl: &mainrepourl 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
main_repobranch: &mainbranch main

argocd_projects:
  - *mgmtclustername
  - *prodclustername

generic_clusterconfig: 
  appsetname: generic-cluster-config
  path: clusters/all/clusterconfig/
  generatorclusters: []

install_oauth:
  appsetname: install-oauth
  path: clusters/all/authentication-identityprovider/overlays/default
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

# A Collection of operators which will be deployed on ALL clusters.
install_operator_collection:
  appsetname: install-operator-collection
  path: components/operators/collection
  generatorclusters: []
  autosync_enabled: false # should be disabled for operators

# A collection of MANAGEMENT operators, installed usually on the management cluster only.
install_mgmt_operator_collection:
  appsetname: install-mgmt-operator-collection
  path: components/operators/collection-management-operators
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

# A Collection of OPTIONAL operators which will be deployed on ALL clusters.
install_optional_operator_collection:
  appsetname: install-optional-operator-collection
  path: components/operators/collection-optional-operators
  generatorclusters: []
  autosync_enabled: false # should be disabled for operators


init_rhacs_central:
  appname: in-cluster-init-rhacs-central
  server: *mgmtcluster
  project: default 
  source: 
    path:  clusters/management-cluster/init_advanced_cluster_security/
    repourl: *mainrepourl
    targetrevision: *mainbranch  

rhacs_demo_app:
  appname: in-cluster-rhacs-demo-app
  server: *mgmtcluster
  project: default 
  source: 
    path:  components/apps/rhacs-demo-applications/
    repourl: *mainrepourl
    targetrevision: *mainbranch  

install_openshift_container_storage:
  appsetname: install-openshift-container-storage
  path: components/operators/openshift-container-storage/overlays/stable
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

install_application_gitops:
  appsetname: install-application-gitops
  path: tenants/management-gitops
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

general:
  argocd_project: 'default'
  source: 
    repourl: *mainrepourl
  branch: *mainbranch 
