# General values
#

# Set cluster names ... Unfortunately the openshift-gitops operator keeps removing the secret of the *mgmtclustername (local cluster), therefor we switch ti list generator
# https://issues.redhat.com/browse/GITOPS-1777
mgmt-cluster: &mgmtcluster https://kubernetes.default.svc
mgmt-cluster-name: &mgmtclustername in-cluster
production-cluster: &prodcluster https://api.ocp.ispworld.at:6443
production-cluster-name: &prodclustername prod

main_repourl: &mainrepourl 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
main_repobranch: &mainbranch main

argocd_projects:
  - *mgmtclustername
  - *prodclustername

applicationsets:
  generic_clusterconfig: 
    enabled: true
    appsetname: generic-cluster-config
    path: clusters/all/clusterconfig/
    per_cluster_helm_values: true
    generatorclusters: []

  install_oauth:
    enabled: true
    path: clusters/all/authentication-identityprovider/overlays/default
    generatorlist:
      - clustername:  *mgmtclustername
        clusterurl: *mgmtcluster
    autosync_enabled: false # should be disabled for operators

  install_netobserv_incl_loki_techpreview:
    enabled: true
    path: clusters/all/network_observer
    generatorlist:
      - clustername:  *mgmtclustername
        clusterurl: *mgmtcluster
    autosync_enabled: false

  # A Collection of operators which will be deployed on ALL clusters.
  install-operator-collection:
    enabled: true
    path: components/operators/collection
    generatorclusters: []
    autosync_enabled: false # should be disabled for operators

  # A collection of MANAGEMENT operators, installed usually on the management cluster only.
  install-mgmt-operator-collection:
    enabled: true
    path: components/operators/collection-management-operators
    generatorlist:
      - clustername:  *mgmtclustername
        clusterurl: *mgmtcluster
    autosync_enabled: false # should be disabled for operators

  # A Collection of OPTIONAL operators which will be deployed on ALL clusters.
  install_optional_operator_collection:
    enabled: true
    path: components/operators/collection-optional-operators
    generatorclusters: []
    autosync_enabled: false # should be disabled for operators

  install_application_gitops:
    enabled: true
    appsetname: install-application-gitops
    path: tenants/management-gitops
    generatorlist:
      - clustername:  *mgmtclustername
        clusterurl: *mgmtcluster
    autosync_enabled: false # should be disabled for operators

applications:
  in-cluster-init-rhacs-central:
    enabled: true
    server: *mgmtcluster
    project: default 
    source: 
      path:  clusters/management-cluster/init_advanced_cluster_security/
      repourl: *mainrepourl
      targetrevision: *mainbranch  

  in-cluster-rhacs-demo-app:
    enabled: true
    server: *mgmtcluster
    project: default 
    source: 
      path:  components/apps/rhacs-demo-applications/
      repourl: *mainrepourl
      targetrevision: *mainbranch  

install_openshift_container_storage:
  appsetname: install-openshift-container-storage
  path: components/operators/openshift-container-storage/overlays/stable
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

general:
  argocd_project: 'default'
  source: 
    repourl: *mainrepourl
  branch: *mainbranch 
