# General values
#

# Set cluster names ... Unfortunately the openshift-gitops operator keeps removing the secret of the *mgmtclustername (local cluster), therefor we switch ti list generator
# https://issues.redhat.com/browse/GITOPS-1777
mgmt-cluster: &mgmtcluster https://kubernetes.default.svc
mgmt-cluster-name: &mgmtclustername in-cluster
production-cluster: &prodcluster https://api.ocp.ispworld.at:6443
production-cluster-name: &prodclustername prod

main_repourl: &mainrepourl 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
main_repobranch: &mainbranch main

argocd_projects:
  - *mgmtclustername
  - *prodclustername

generic_clusterconfig: 
  appsetname: generic-cluster-config
  path: clusters/all/clusterconfig/
  generatorclusters: []

install_advanced_cluster_security:
  appsetname: install-rhacs
  path: components/operators/advanced_cluster_security/overlays/latest
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
    - clustername:  *prodclustername
      clusterurl: *prodcluster
  autosync_enabled: false # should be disabled for operators

init_rhacs_central:
  appname: in-cluster-init-rhacs-central
  server: *mgmtcluster
  project: default 
  source: 
    path:  clusters/management-cluster/init_advanced_cluster_security/
    repourl: *mainrepourl
    targetrevision: *mainbranch  

rhacs_demo_app:
  appname: in-cluster-rhacs_demo_app
  server: *mgmtcluster
  project: default 
  source: 
    path:  components/apps/rhacs-demo-applications/
    repourl: *mainrepourl
    targetrevision: *mainbranch  

install_quay:
  appsetname: install-quay
  path: components/operators/redhat-quay/overlays/stable
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

install_openshift_logging:
  appsetname: openshift-logging
  path: components/operators/openshift-logging/overlays/stable
  generatorclusters: []

install_openshift_servicemesh:
  appsetname: install-servicemesh
  path: components/operators/openshift-servicemesh/overlays/stable
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
    - clustername:  *prodclustername
      clusterurl: *prodcluster
  autosync_enabled: false # should be disabled for operators

install_openshift_tracing:
  appsetname: install-jaeger
  path: components/operators/tracing-operator-jaeger/overlays/stable
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
    - clustername:  *prodclustername
      clusterurl: *prodcluster
  autosync_enabled: false # should be disabled for operators

install_kiali:
  appsetname: install-kiali
  path: components/operators/operator-kiali/overlays/stable
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
    - clustername:  *prodclustername
      clusterurl: *prodcluster
  autosync_enabled: false # should be disabled for operators

install_elasticsearch:
  appsetname: install-elasticsearch
  path: components/operators/openshift-elasticsearch/overlays/default
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

install_openshift_pipelines:
  appsetname: install-openshift-pipelines
  path: components/operators/openshift-pipelines/overlays/stable
  generatorclusters: []
  autosync_enabled: false # should be disabled for operators

install_redhat_sso:
  appsetname: install-redhat-sso
  path: components/operators/redhat-sso/overlays/alpha
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

install_openshift_container_storage:
  appsetname: install-openshift-container-storage
  path: components/operators/openshift-container-storage/overlays/stable
  generatorlist:
    - clustername:  *mgmtclustername
      clusterurl: *mgmtcluster
  autosync_enabled: false # should be disabled for operators

general:
  argocd_project: 'default'
  source: 
    repourl: *mainrepourl
  branch: *mainbranch 



