---
namespace:
  name: netobserv
  create: true

syncwave: '3'

helper-operator:
  operators:
    netobserv-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-operators
        create: false
      subscription:
        channel: v0.2.x
        approval: Automatic
        operatorName: netobserv-operator
        source: community-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false

helper-status-checker:
  enabled: true

  # space separate list of deployments which shall be checked for status
  deployments: "netobserv-controller-manager"

  wait_time: 60  # wait time in seconds for the check-job to verify when the deployments should be ready

  namespace:
    name: openshift-operators

  serviceAccount:
    create: true
    name: "status-checker-netobserv"