annotations:
  artifacthub.io/changes: |
    - kind: added
      description: support git GIT generator
    - kind: added
      description: Release 2.0 allows the usage of multiple sources and a releasemanagement for charts. (ie. dev install version X, prod installs version Y)
    - kind: fixed
      description: Signing Chart
    - kind: added
      description: Added support for Matrix Generator (opinionated)
    - kind: added
      description: Added support for ignoreDifferences definition in ApplicationSet
    - kind: added
      description: Allowing syncwave settings for Application objects
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
apiVersion: v2
description: Takes care of creation of Applications and ApplicationSets
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/helper-argocd
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/argo-icon-color.png
keywords:
- helper
- subchart
- gitops
maintainers:
- email: tjungbau@redhat.com
  name: tjungbauer
name: helper-argocd
sources:
- https://github.com/tjungbauer/helm-charts
version: 2.0.21
