---

helper-operator:
  operators:
    cert-utils-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: cert-utils-operator
        create: true
      subscription:
        channel: alpha
        approval: Automatic
        operatorName: cert-utils-operator
        source: community-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true
    cert-manager:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-cert-manager-operator
        create: true
      subscription:
        channel: tech-preview
        approval: Automatic
        operatorName: openshift-cert-manager-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true

helper-status-checker:
  enabled: true

  operatorName: openshift-cert-manager

  # where operator is installed
  namespace:
    name: openshift-cert-manager-operator

  serviceAccount:
    create: true
    name: "status-checker-cert-manager-operator"
