{{ range $index, $namespace := (lookup "v1" "Namespace" "" "").items }}
kind: Secret
apiVersion: v1
metadata:
  name: xxxx
  namespace: quay-enterprise
stringData:
  xxx: {{ $namespace.metadata.name }}
{{- end }}
