apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.install_advanced_cluster_security.appsetname }}
  namespace: openshift-gitops
spec:
  generators:
  {{- if .Values.install_advanced_cluster_security.clusterlist }}
    {{- range .Values.install_advanced_cluster_security.clusterlist }}
      - clusters:
          selector:
            matchLabels:
              env: {{ .env }}
    {{- end }}
  {{- else }}
    - clusters: {}
  {{- end }}
  template:
    metadata:
      name: >-
          {{ printf "{{ name }}-install-rhacs" }}
    spec:
      project: {{ .Values.general.argocd_project }}
      source:
        repoURL: {{ .Values.general.source.repourl }}
        targetRevision: {{ .Values.general.branch }}
        path: {{ .Values.install_advanced_cluster_security.path }}
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
      destination:
        server:  >-
          {{ printf "{{ server }}" }}
        namespace: default
