apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.etcd_encryption.appsetname }}
  namespace: openshift-gitops
spec:
  generators:
  {{- if .Values.etcd_encryption.clusterlist }}
    {{- range .Values.etcd_encryption.clusterlist }}
      - clusters:
        selector:
          matchLabels:
            env: {{ .env }}
    {{- end }}
  {{- else }}
    - clusters: {}
  {{- end }}  
  template:
    metadata:
      name: >-
          {{ printf "{{ name }}-etcd-encryption" }}
    spec:
      project: {{ .Values.general.argocd_project }}
      source:
        repoURL: {{ .Values.general.source.repourl }}
        targetRevision: {{ .Values.general.branch }}
        path: {{ .Values.etcd_encryption.path }}
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
      destination:
        server:  >-
          {{ printf "{{ server }}" }}
        namespace: default
