apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oauth-ldap.yaml

patches:
  - patch: |-
      - op: replace 
        path: /spec/source/path
        value: clusters/management-cluster/config/oauth-cluster/overlays/ldap
    target:
      kind: Application