apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - acs-backup-cronjob-app.yaml

patches:
  - patch: |-
      - op: replace 
        path: /spec/source/path
        value: .
    target:
      kind: Application
  - patch: |-
      - op: replace 
        path: /spec/source/repoURL
        value: https://github.com/tjungbauer/stackrox-backup-cronjob
    target:
      kind: Application