apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

commonLabels:
  created-by: cluster-bootstrap
  author: 'Thomas_Jungbauer'
  clustername: 'Management_Cluster'

resources:
  - ../console-banner/base
  - ../etcd-encryption/base
  - ../advanced-cluster-security/base
  - ../openshift-logging/base

patches:
  - patch: |-
      - op: replace 
        path: /spec/destination/server
        value: https://kubernetes.default.svc
    target:
      kind: Application
  - patch: |-
      - op: replace 
        path: /spec/source/targetRevision
        value: main
    target:
      kind: Application
  - patch: |-
      - op: replace 
        path: /spec/source/repoURL
        value: https://github.com/tjungbauer/openshift-cluster-bootstrap
    target:
      kind: Application
