---
generic-cluster-config:
  console:
    yamlsamples:
      secret-yaml-sample:
        enabled: true
        targetResource:
          apiv: "v1"
          kind: Secret
        title: "Secret based on cleartext values"
        descr: "This is an example to create a Secret based on clear-text values"
        yamlDef: |+
              apiVersion: v1
              kind: Secret
              metadata:
                name: example
              type: Opaque
              stringData:
                email: youremail@address.com
                password: YourSuperPassword
